### ISSUE TITLE
print error for Application class

### ISSUE THREAD

**Issue by Vic-ong** [23maverick23/oaxmlapi#12]
Hi,

I found that when I tried to print the details of the Application, it fails. This is because the client version variable is wrong: 

should be edited to:
`def __str__(self):
        return "%s (v%s)" % (self.client, self.client_version)`

original code on commands.py of Application class:
 `   def __str__(self):
        return "%s (v%s)" % (self.client, self.version)`

**Comment by 23maverick23** [comment]
Thanks for submitting. Feel free to submit a PR. Otherwise I can try and get to this over the weekend.
